#!/usr/bin/env python3
"""Regenerate selfhost/aes_hw.tin, seal's AES-CTR, GHASH and CPU-check leaves, from
tools/arch/aes-gcm-*.S (needs clang). The code generators emit these bytes for the
seal.aes_hw_ctr, seal.aes_hw_subword, seal.ghash_hw and seal.aes_hw_cpu placeholders."""
import argparse
from pathlib import Path
import struct
import subprocess
import tempfile
from gen_memory_fast import functions

ROOT = Path(__file__).resolve().parents[1]
NAMES = {'arm64': ('aes_hw_ctr', 'aes_hw_subword', 'ghash_hw'), 'amd64': ('aes_hw_cpu', 'aes_hw_ctr', 'aes_hw_subword', 'ghash_hw')}


def generate():
    text = ['// Generated by tools/gen_aes_hw.py from tools/arch/aes-gcm-*.S.']
    with tempfile.TemporaryDirectory() as tmp:
        for arch, target in [('arm64', 'aarch64-linux-gnu'), ('amd64', 'x86_64-linux-gnu')]:
            obj = Path(tmp)/f'{arch}.o'
            subprocess.run(['clang', '-target', target, '-c', str(ROOT/f'tools/arch/aes-gcm-{arch}.S'), '-o', str(obj)], check=True)
            table = functions(obj, NAMES[arch])
            text += ['', f'// aes_hw_{arch} is the machine code of seal.NAME (NAME without the package), or 0.',
                     f'fn aes_hw_{arch}(name) {{', '    let hex=0;']
            for name in NAMES[arch]:
                data = table[name]
                if arch == 'arm64':
                    data = ''.join(f'{v[0]:08x}' for v in struct.iter_unpack('<I', data))
                else:
                    data = data.hex()
                text.append(f'    if streq(name,"seal.{name}") {{ hex="{data}"; }}')
            text += ['    if !hex { return 0; }', '    let v=vec_new(); let i=0;', '    while load8(hex+i) != 0 {']
            if arch == 'arm64':
                text.append('        raw(v,hex_word(hex+i)); i=i+8;')
            else:
                text.append('        vec_push(v,num_digit(load8(hex+i))*16+num_digit(load8(hex+i+1))); i=i+2;')
            text += ['    }', '    return v;', '}']
    return '\n'.join(text)+'\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT/'selfhost/aes_hw.tin'
    result = generate()
    if args.check:
        assert path.read_text() == result, 'AES machine code is stale'
    else:
        path.write_text(result)
